# Generated by Django 4.2.7 on 2023-12-23 06:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_payment_amount_paid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderproduct',
            name='color',
        ),
        migrations.RemoveField(
            model_name='orderproduct',
            name='size',
        ),
    ]
